using System;

namespace AgOpenGPS.Api.Client.Models
{
    /// <summary>
    /// Strongly-typed application state model.
    /// Contains all application state that is broadcast from backend to frontend.
    /// </summary>
    public class ApplicationState
    {
        /// <summary>
        /// Timestamp when this state was generated by the backend.
        /// Updated at 4 Hz (every 250ms) by ApplicationOrchestrator.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the GNSS (GPS) state.
        /// Contains position, motion, quality, and health metrics from GPS receiver.
        /// May be null if GPS data is not yet available or signal is lost.
        /// </summary>
        public GnssState? Gnss { get; set; }
    }
}
